export const quizData = {
  id: "quiz_1",
  title: "General Knowledge Quiz",
  questions: [
    {
      id: "q1",
      text: "2 + 2 = ?",
      options: [
        { id: "o1", text: "3" },
        { id: "o2", text: "4" },
        { id: "o3", text: "5" },
        { id: "o4", text: "6" },
      ],
      correctOptionId: "o2",
    },
    {
      id: "q2",
      text: "Capital of Japan?",
      options: [
        { id: "o5", text: "Seoul" },
        { id: "o6", text: "Tokyo" },
        { id: "o7", text: "Beijing" },
        { id: "o8", text: "Bangkok" },
      ],
      correctOptionId: "o6",
    },
    {
      id: "q3",
      text: "HTML гэж юу вэ?",
      options: [
        { id: "o9", text: "Programming language" },
        { id: "o10", text: "Markup language" },
        { id: "o11", text: "Database" },
        { id: "o12", text: "OS" },
      ],
      correctOptionId: "o10",
    },
    {
      id: "q4",
      text: "React аль компани бүтээсэн бэ?",
      options: [
        { id: "o13", text: "Google" },
        { id: "o14", text: "Facebook" },
        { id: "o15", text: "Microsoft" },
        { id: "o16", text: "Amazon" },
      ],
      correctOptionId: "o14",
    },
    {
      id: "q5",
      text: "CSS юунд хэрэглэгддэг вэ?",
      options: [
        { id: "o17", text: "Logic" },
        { id: "o18", text: "Styling" },
        { id: "o19", text: "Database" },
        { id: "o20", text: "API" },
      ],
      correctOptionId: "o18",
    },
    {
      id: "q6",
      text: "1 byte = ? bits",
      options: [
        { id: "o21", text: "4" },
        { id: "o22", text: "8" },
        { id: "o23", text: "16" },
        { id: "o24", text: "32" },
      ],
      correctOptionId: "o22",
    },
    {
      id: "q7",
      text: "JavaScript аль талд ажилладаг вэ?",
      options: [
        { id: "o25", text: "Frontend" },
        { id: "o26", text: "Backend" },
        { id: "o27", text: "Both" },
        { id: "o28", text: "None" },
      ],
      correctOptionId: "o27",
    },
    {
      id: "q8",
      text: "MongoDB ямар төрлийн DB вэ?",
      options: [
        { id: "o29", text: "Relational" },
        { id: "o30", text: "NoSQL" },
        { id: "o31", text: "Graph" },
        { id: "o32", text: "Key-value only" },
      ],
      correctOptionId: "o30",
    },
    {
      id: "q9",
      text: "Next.js юунд ашиглагддаг вэ?",
      options: [
        { id: "o33", text: "Backend only" },
        { id: "o34", text: "Frontend framework" },
        { id: "o35", text: "Fullstack framework" },
        { id: "o36", text: "Mobile app" },
      ],
      correctOptionId: "o35",
    },
    {
      id: "q10",
      text: "HTTP status 404 юу гэсэн үг вэ?",
      options: [
        { id: "o37", text: "OK" },
        { id: "o38", text: "Unauthorized" },
        { id: "o39", text: "Not Found" },
        { id: "o40", text: "Server Error" },
      ],
      correctOptionId: "o39",
    },
    {
      id: "q11",
      text: "Git юунд хэрэгтэй вэ?",
      options: [
        { id: "o41", text: "Database" },
        { id: "o42", text: "Version control" },
        { id: "o43", text: "Hosting" },
        { id: "o44", text: "Compiler" },
      ],
      correctOptionId: "o42",
    },
    {
      id: "q12",
      text: "TypeScript гэж юу вэ?",
      options: [
        { id: "o45", text: "JS superset" },
        { id: "o46", text: "Database" },
        { id: "o47", text: "Framework" },
        { id: "o48", text: "Browser" },
      ],
      correctOptionId: "o45",
    },
    {
      id: "q13",
      text: "Node.js юунд ашиглагддаг вэ?",
      options: [
        { id: "o49", text: "Frontend UI" },
        { id: "o50", text: "Backend runtime" },
        { id: "o51", text: "CSS styling" },
        { id: "o52", text: "Design tool" },
      ],
      correctOptionId: "o50",
    },
    {
      id: "q14",
      text: "REST API гэж юу вэ?",
      options: [
        { id: "o53", text: "Protocol" },
        { id: "o54", text: "Architecture style" },
        { id: "o55", text: "Language" },
        { id: "o56", text: "Library" },
      ],
      correctOptionId: "o54",
    },
    {
      id: "q15",
      text: "JSON юунд хэрэглэгддэг вэ?",
      options: [
        { id: "o57", text: "Data exchange" },
        { id: "o58", text: "Styling" },
        { id: "o59", text: "Database only" },
        { id: "o60", text: "Compiler" },
      ],
      correctOptionId: "o57",
    },
    {
      id: "q16",
      text: "Tailwind CSS юу вэ?",
      options: [
        { id: "o61", text: "Framework" },
        { id: "o62", text: "Utility-first CSS" },
        { id: "o63", text: "Language" },
        { id: "o64", text: "Database" },
      ],
      correctOptionId: "o62",
    },
    {
      id: "q17",
      text: "useState юу хийдэг вэ?",
      options: [
        { id: "o65", text: "Routing" },
        { id: "o66", text: "State хадгална" },
        { id: "o67", text: "API call" },
        { id: "o68", text: "Styling" },
      ],
      correctOptionId: "o66",
    },
    {
      id: "q18",
      text: "Prisma юу вэ?",
      options: [
        { id: "o69", text: "ORM" },
        { id: "o70", text: "Frontend lib" },
        { id: "o71", text: "CSS tool" },
        { id: "o72", text: "OS" },
      ],
      correctOptionId: "o69",
    },
    {
      id: "q19",
      text: "PostgreSQL ямар DB вэ?",
      options: [
        { id: "o73", text: "NoSQL" },
        { id: "o74", text: "Relational" },
        { id: "o75", text: "Graph" },
        { id: "o76", text: "Cache" },
      ],
      correctOptionId: "o74",
    },
    {
      id: "q20",
      text: "API гэдэг нь юу вэ?",
      options: [
        { id: "o77", text: "UI design" },
        { id: "o78", text: "Connection between systems" },
        { id: "o79", text: "Database" },
        { id: "o80", text: "Language" },
      ],
      correctOptionId: "o78",
    },
  ],
};
